version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - "8089:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
      
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=epharmacy@123
      - MYSQL_DATABASE=epharmacy_db
      - MYSQL_USER=msit
      - MYSQL_PASSWORD=msit
    ports:
      - "3307:3306"
    container_name: mysql
      
      
